### ISSUE TITLE
Built release doesn't contain compiled assets

### ISSUE THREAD

**Issue by Htbaa** [OpenWebconcept/open-government-publications#1]
The current build pipeline doesn't include the generated assets that are being built by Webpack. This seems to be caused by the fact that `cross-env` is not available (https://github.com/OpenWebconcept/open-government-publications/runs/7561890327?check_suite_focus=true#step:6:5)

The reason `cross-env` isn't available is because Node dependencies aren't being installed. This can be fixed by adding a new step to the GitHub Actions file, see https://github.com/OpenWebconcept/plugin-datainmap/blob/develop/.github/workflows/build.yml#L22 for an example. Bonus: add caching for NPM for improved build times.

**Comment by sanderdekroon** [comment]
Somehow I have totally missed that. Thank you for creating this issue :). It should now be fixed by [this PR](https://github.com/OpenWebconcept/open-government-publications/pull/2)
